update ssh workflow

diff --git a/.github/workflows/terraform-cicd.yml b/.github/workflows/terraform-cicd.yml
--- a/.github/workflows/terraform-cicd.yml
+++ b/.github/workflows/terraform-cicd.yml
@@ -51,17 +51,16 @@ jobs:
 
       - name: Wait for SSH to become available
         run: |
-          for i in {1..10}; do
-            echo "⏳ Attempt $i: Trying SSH to $EC2_IP..."
-            if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i ~/.ssh/id_rsa $USER@$EC2_IP "echo '✅ SSH connected'" 2>/dev/null; then
-              echo "✅ SSH successful on attempt $i"
-              exit 0
-            else
-              echo "❌ SSH failed (attempt $i), retrying in 10 seconds..."
-              sleep 10
-            fi
-          done
-          echo "❌ Timeout: SSH connection could not be established after 10 attempts."
+          echo "Getting EC2 Public IP..."
+          raw_ip=$(terraform output ec2_public_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | tail -n 1)
+          echo "Extracted IP: $raw_ip"
+
+          if [[ ! "$raw_ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid IP format: $raw_ip"
+            exit 1
+          fi
+
+          echo "EC2_IP=$raw_ip" >> $GITHUB_ENV
 
       - name: Setup SSH
         run: |
